version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    env_file: .env
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    networks:
      - backend_network

  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge